services:
    db:
        image: postgres:17
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DOCKER_POSTGRES_USER}
            POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
            POSTGRES_DB: ${DOCKER_POSTGRES_DB}
        volumes:
            - db:/var/lib/postgresql/data

    matomo_db:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MATOMO_DB_ROOT_PASSWORD:-rootpassword}
            MYSQL_DATABASE: ${MATOMO_DB_NAME:-matomo}
            MYSQL_USER: ${MATOMO_DB_USER:-matomo}
            MYSQL_PASSWORD: ${MATOMO_DB_PASSWORD:-matomo}
        volumes:
            - matomo_db:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password

    matomo:
        image: matomo:latest
        restart: unless-stopped
        environment:
            - MATOMO_DATABASE_HOST=matomo_db
            - MATOMO_DATABASE_ADAPTER=mysql
            - MATOMO_DATABASE_TABLES_PREFIX=matomo_
            - MATOMO_DATABASE_USERNAME=${MATOMO_DB_USER:-matomo}
            - MATOMO_DATABASE_PASSWORD=${MATOMO_DB_PASSWORD:-matomo}
            - MATOMO_DATABASE_DBNAME=${MATOMO_DB_NAME:-matomo}
        volumes:
            - matomo_data:/var/www/html
        depends_on:
            - matomo_db

    adminer:
        image: adminer:latest
    server:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            - NODE_ENV=development
            - PORT=5000
            - DATABASE_URL=postgresql://${DOCKER_POSTGRES_USER}:${DOCKER_POSTGRES_PASSWORD}@db:5432/${DOCKER_POSTGRES_DB}
            - MATOMO_URL=http://matomo
            - MATOMO_SITE_ID=${MATOMO_SITE_ID:-1}
            - SERVER_SENTRY_DSN=${SERVER_SENTRY_DSN:-""}
        depends_on:
            - db
    frontend:
        build:
            context: ../frontend
            dockerfile: Dockerfile
        working_dir: /app
        volumes:
            - ../frontend:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - VITE_API_URL=/api
            - VITE_MATOMO_URL=/matomo
            - VITE_MATOMO_SITE_ID=${MATOMO_SITE_ID:-1}
            - VITE_SENTRY_DSN=${VITE_SENTRY_DSN:-""}
        depends_on:
            - server

    reverse-proxy:
        build:
            context: ../reverse-proxy
        ports:
            - "80:80"
        depends_on:
            - frontend
            - server
            - matomo
            - adminer


volumes:
    db:
    matomo_db:
    matomo_data:
