services:
    db:
        image: postgres:17
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DOCKER_POSTGRES_USER}
            POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
            POSTGRES_DB: ${DOCKER_POSTGRES_DB}
        ports:
            - '${DOCKER_POSTGRES_PORT}:5432'
        volumes:
            - db:/var/lib/postgresql/data
    adminer:
        image: adminer:latest
        ports:
            - 8080:8080
    server:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - '${DOCKER_SERVER_PORT}:5000'
        environment:
            - NODE_ENV=development
            - PORT=5000
            - DATABASE_URL=postgresql://${DOCKER_POSTGRES_USER}:${DOCKER_POSTGRES_PASSWORD}@db:5432/${DOCKER_POSTGRES_DB}
        depends_on:
            - db
    frontend:
        build:
            context: ../frontend
            dockerfile: Dockerfile
        working_dir: /app
        volumes:
            - ../frontend:/app
            - /app/node_modules
        ports:
            - '${DOCKER_FRONTEND_PORT}:5174'
        environment:
            - NODE_ENV=development
            - VITE_API_URL=http://localhost:${DOCKER_SERVER_PORT}/api
        depends_on:
            - server

volumes:
    db:
